### ISSUE TITLE
macbook pro 16 , catalina10.15.5 install error

### ISSUE THREAD

**Issue by drst3in** [tholu/homebrew-tap#10]
brew install --with-unicode-path  tholu/tap/subversion18

Updating Homebrew...
==> Installing subversion18 from tholu/tap
==> Downloading https://gist.githubusercontent.com/tholu/fb5d30c586e33b53ecba/raw/a266b1aa01f9
Already downloaded: /Users/drst3in/Library/Caches/Homebrew/downloads/5e379d7e8de627cc4210cf1e12a762045bfd327bdaecc90df234a152482bda6e--svn_1.8.x_darwin_unicode_precomp.patch
==> Downloading https://www.apache.org/dyn/closer.cgi?path=serf/serf-1.3.9.tar.bz2
Already downloaded: /Users/drst3in/Library/Caches/Homebrew/downloads/3f4e2cb0f268fb9db7a761edccb60bdbdacb9923f8b2140e8c0a30b6792958a6--serf-1.3.9.tar.bz2
==> Downloading https://www.apache.org/dyn/closer.cgi?path=subversion/subversion-1.8.16.tar.bz
Already downloaded: /Users/drst3in/Library/Caches/Homebrew/downloads/739776cd56d0ee92a7e0915f4ea1bade82c80b68ef6526f210aac0684bac7786--subversion-1.8.16.tar.bz2
==> Patching
patching file configure
Hunk #1 succeeded at 25433 (offset 67 lines).
patching file subversion/bindings/swig/perl/native/Makefile.PL.in
patching file build/get-py-info.py
==> Applying svn_1.8.x_darwin_unicode_precomp.patch
patching file subversion/libsvn_subr/io.c
patching file subversion/libsvn_subr/path.c
patching file subversion/svn/proplist-cmd.c
patching file subversion/svn/status-cmd.c
==> scons PREFIX=/usr/local/Cellar/subversion18/1.8.16/libexec/serf GSSAPI=/usr CC=/usr/bin/cl
Last 15 lines from /Users/drst3in/Library/Logs/Homebrew/subversion18/01.scons:
CFLAGS=-Os -w -pipe -march=nehalem -mmacosx-version-min=10.15 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
LINKFLAGS=-L/usr/local/opt/sqlite/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
OPENSSL=/usr/local/opt/openssl@1.1
APR=/usr/local/opt/apr
APU=/usr/local/opt/apr-util

scons: Reading SConscript files ...
  File "/private/tmp/subversion18--serf-20200619-3848-160qzxe/serf-1.3.9/SConstruct", line 186

    print 'Warning: Used unknown variables:', ', '.join(unknown.keys())

          ^

SyntaxError: invalid syntax

**Comment by drst3in** [comment]
brew config


HOMEBREW_VERSION: 2.4.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 28ed0801ed5807e176e62a3ba66e47ec867ec17d
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 775c2ddc2b6be4fc21727ae34aa8d937f997224b
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 12
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.1
macOS: 10.15.5-x86_64
CLT: 1103.0.32.62
Xcode: N/A

----------------------------------------------
python --version
Python 2.7.16

**Comment by tholu** [comment]
I can reproduce the problem when trying to reinstall with:

`brew reinstall --with-unicode-path tholu/tap/subversion18`

Not immediately sure what changed, will try to check this.

**Comment by tholu** [comment]
Same exact problem as in #5 - so it has to do with Python.

**Comment by tholu** [comment]
It seems like the scons 3.1.2 formula now uses explicitly Python 3.8, which does not play well with the SConstruct file of serf 1.3.9.

**Comment by drst3in** [comment]
Thank you.
The scon library seems to be the problem.
However, even if brew installs scon2.xx, it will force scon 3.xx to be reinstalled....
Any good ideas?

**Comment by tholu** [comment]
Detecting the Python version and patching the serf SConstruct file so it works with Python 3? Or using a virtualenv with Python 2 to build everything. Not sure what the best practice is here.

**Comment by jetbee** [comment]
I also cannot install subversion18 on my new 10.15.5 Catalina environment.
I tried install with python 2.7, 3.7, 3.8. All failed at that place same as drst3in.
As drst3in said, scons3.1.2 has something problems I think.

**Comment by drst3in** [comment]
> I also cannot install subversion18 on my new 10.15.5 Catalina environment.
> I tried install with python 2.7, 3.7, 3.8. All failed at that place same as drst3in.
> As drst3in said, scons3.1.2 has something problems I think.

---------------------------------------------------------------------------------------------

It cannot be installed using brew, but you can install and use subversion of macport using macport.

**Comment by tholu** [comment]
Same problem here with building on Windows: http://mail-archives.apache.org/mod_mbox/serf-dev/202004.mbox/browser

**Comment by tholu** [comment]
Fixed in https://github.com/tholu/homebrew-tap/commit/88a1814c6eb4bb256829de16290d941d39264226 - let me know if you still have problems. Tested on MacOS 11 Big Sur as well.
