### ISSUE TITLE
Does not work with Big Sur

### ISSUE THREAD

**Issue by michabbs** [tholu/homebrew-tap#13]
After upgrade to Big Sur it stopped to work. I tried to reinstall, but no success... :-(

Dirty hack: I commented out lines no. 39, 102, 131. -> The compilation succeed, reinstall went ok. Svn seems to work for now.

**Comment by tholu** [comment]
Fixed in 914f2b390882d1c2cc8faab5f0f19fda15d7301d (and dramatically simplified the formula in the process). Thanks for reporting!
