### ISSUE TITLE
SConstruct SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by jetbee** [tholu/homebrew-tap#5]
scons: Reading SConscript files ...
  File "/private/tmp/subversion18--serf-20181002-42200-zwqvgw/serf-1.3.8/SConstruct", line 180

    print 'Unknown variables:', ', '.join(unknown.keys())

                             ^

SyntaxError: invalid syntax

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/tholu/homebrew-tap/issues

**Comment by tholu** [comment]
@jetbee Can you post the full output when you tried to install the formula? And share some information about your environment(`brew config`).

I can't reproduce it, and I used this command to install it (after removing it): `brew install subversion18 --with-unicode-path`

**Comment by jetbee** [comment]
Thanks you for reply(^^)
Here is my full console log.

`(idiogw-sim) yoga2602:idio_commsitesystem gen$ brew tap tholu/tap
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core, homebrew/cask).
==> New Formulae
opensubdiv                               tdlib
==> Updated Formulae
abcde                                    jfrog-cli-go
aircrack-ng                              jhipster
aws-okta                                 joplin
ballerina                                kibana
bcal                                     kubernetes-service-catalog-client
caffe                                    landscaper
cgal                                     links
clamav                                   logstash
cmake                                    metabase
commandbox                               nginx
container-diff                           numpy
darksky-weather                          poppler
dita-ot                                  rakudo-star
dnscrypt-proxy                           safe
doctl                                    sbcl
elasticsearch                            skaffold
ffmbc                                    skafos
fpc                                      suricata
git                                      swiftgen
goenv                                    telegraf
haproxy                                  terragrunt
jenkins                                  topgrade
jetty                                    vert.x
jetty-runner                             vim
==> Deleted Formulae
asciinema2gif       casperjs            qt@5.5              sonarlint

(idiogw-sim) yoga2602:idio_commsitesystem gen$ brew install --with-unicode-path tholu/tap/subversion18

==> Installing subversion18 from tholu/tap
==> Downloading https://www.apache.org/dyn/closer.cgi?path=subversion/subversion
Already downloaded: /Users/gen/Library/Caches/Homebrew/downloads/739776cd56d0ee92a7e0915f4ea1bade82c80b68ef6526f210aac0684bac7786--subversion-1.8.16.tar.bz2
==> Downloading https://gist.githubusercontent.com/tholu/fb5d30c586e33b53ecba/ra
Already downloaded: /Users/gen/Library/Caches/Homebrew/downloads/5e379d7e8de627cc4210cf1e12a762045bfd327bdaecc90df234a152482bda6e--svn_1.8.x_darwin_unicode_precomp.patch
==> Patching
patching file configure
Hunk #1 succeeded at 25433 (offset 67 lines).
patching file subversion/bindings/swig/perl/native/Makefile.PL.in
patching file build/get-py-info.py
==> Applying svn_1.8.x_darwin_unicode_precomp.patch
patching file subversion/libsvn_subr/io.c
patching file subversion/libsvn_subr/path.c
patching file subversion/svn/proplist-cmd.c
patching file subversion/svn/status-cmd.c
==> Downloading https://archive.apache.org/dist/serf/serf-1.3.8.tar.bz2
Already downloaded: /Users/gen/Library/Caches/Homebrew/downloads/21bc402f7e59867bb8a6027535b1c5cda70bae29838d2398fff3d60ff35fdf97--serf-1.3.8.tar.bz2
==> /usr/local/opt/scons/bin/scons PREFIX=/usr/local/Cellar/subversion18/1.8.16/
Last 15 lines from /Users/gen/Library/Logs/Homebrew/subversion18/01.scons:
CFLAGS=-Os -w -pipe -march=native -mmacosx-version-min=10.13 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk
LINKFLAGS=-L/usr/local/opt/sqlite/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl/lib -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk
OPENSSL=/usr/local/opt/openssl
APR=/usr/local/opt/apr
APU=/usr/local/opt/apr-util

scons: Reading SConscript files ...
  File "/private/tmp/subversion18--serf-20181004-12801-93q5vm/serf-1.3.8/SConstruct", line 180

    print 'Unknown variables:', ', '.join(unknown.keys())

                             ^

SyntaxError: invalid syntax


If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/tholu/homebrew-tap/issues

(idiogw-sim) yoga2602:idio_commsitesystem gen$ 
`

**Comment by tholu** [comment]
Please post the output of:

`brew config`

Then try:

`brew cleanup`
`brew remove subversion18`
`brew install subversion18 --with-unicode-path`

**Comment by jetbee** [comment]
Thanks!
(Uhmm, tap function of brew is little bit complicated for me for me.)

===============
(hack) yoga2602-2:~ gen$ brew config
HOMEBREW_VERSION: 1.7.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: f239b7a62790cfb4f33bda9aab7597d43f1b1e3b
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 364de9009d5c7ce77ddbee00537550cb6cc0f370
Core tap last commit: 2 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT: git
HOMEBREW_MACOS_VERSION_NUMERIC: 101306
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.6-x86_64
CLT: 10.0.0.0.1.1535735448
CLT headers: N/A
Xcode: N/A
XQuartz: N/A
(hack) yoga2602-2:~ gen$ brew cleanup
(hack) yoga2602-2:~ gen$ brew remove subversion18
Error: No such keg: /usr/local/Cellar/subversion18
(hack) yoga2602-2:~ gen$ brew install subversion18 --with-unicode-path
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core, homebrew/cask).
==> New Formulae
i2pd
==> Updated Formulae
apache-geode                             ipv6calc
app-engine-java                          jhipster
ark                                      krakend
bettercap                                kubernetes-service-catalog-client
bitcoin                                  libepoxy
checkbashisms                            libphonenumber
clipper                                  mariadb
exercism                                 meson
fail2ban                                 micronaut
flatbuffers                              mkvtoolnix
geckodriver                              mpv
git                                      nodebrew
grakn                                    nomad
gst-editing-services                     orc-tools
gst-libav                                phoronix-test-suite
gst-plugins-bad                          phpunit
gst-plugins-base                         puzzles
gst-plugins-good                         shpotify
gst-plugins-ugly                         strongswan
gst-python                               unrar
gst-rtsp-server                          yamllint
gst-validate                             ykman
gstreamer                                youtube-dl
highlight                                yubico-piv-tool
i2p                                      zenity

==> Installing subversion18 from tholu/tap
==> Downloading https://www.apache.org/dyn/closer.cgi?path=subversion/subversion
==> Downloading from http://www-us.apache.org/dist/subversion/subversion-1.8.16.

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://archive.apache.org/dist/subversion/subversion-1.8.16.tar
######################################################################## 100.0%
==> Downloading https://gist.githubusercontent.com/tholu/fb5d30c586e33b53ecba/ra
######################################################################## 100.0%
==> Patching
patching file configure
Hunk #1 succeeded at 25433 (offset 67 lines).
patching file subversion/bindings/swig/perl/native/Makefile.PL.in
patching file build/get-py-info.py
==> Applying svn_1.8.x_darwin_unicode_precomp.patch
patching file subversion/libsvn_subr/io.c
patching file subversion/libsvn_subr/path.c
patching file subversion/svn/proplist-cmd.c
patching file subversion/svn/status-cmd.c
==> Downloading https://archive.apache.org/dist/serf/serf-1.3.8.tar.bz2
######################################################################## 100.0%
==> /usr/local/opt/scons/bin/scons PREFIX=/usr/local/Cellar/subversion18/1.8.16/
Last 15 lines from /Users/gen/Library/Logs/Homebrew/subversion18/01.scons:
CFLAGS=-Os -w -pipe -march=native -mmacosx-version-min=10.13 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk
LINKFLAGS=-L/usr/local/opt/sqlite/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl/lib -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk
OPENSSL=/usr/local/opt/openssl
APR=/usr/local/opt/apr
APU=/usr/local/opt/apr-util

scons: Reading SConscript files ...
  File "/private/tmp/subversion18--serf-20181006-3202-15v7zut/serf-1.3.8/SConstruct", line 180

    print 'Unknown variables:', ', '.join(unknown.keys())

                             ^

SyntaxError: invalid syntax


If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/tholu/homebrew-tap/issues


===============

**Comment by tholu** [comment]
Thanks, please run:

`brew upgrade`
`brew cleanup`

And let me know the output of:

`which python`
`python --version`

**Comment by jetbee** [comment]
Omg. my python environment is 3.7.
===
(hack) mori:~ gen$ which python
/Users/gen/.pyenv/shims/python
(hack) mori:~ gen$ python --version
Python 3.7.0
(hack) mori:~ gen$ 
===

I'm going to try with macOS builtin python environment.

**Comment by jetbee** [comment]
OMG. My python environment was 3.7.0...
I've switched python version to 2.7.15 then It worked.
That was really easy mistake...
I was very sorry.

=====
(hack) mori:~ gen$ python --version
Python 3.7.0
(hack) mori:~ gen$ pyenv global 2.7.15
mori:~ gen$ brew cleanup
Removing: /Users/gen/Library/Caches/Homebrew/subversion18--patch--2eaee628e3161bce4b1697660281cab30f42265369bfa7074ea435e441d543e7.patch... (4.4KB)
==> This operation has freed approximately 4.4KB of disk space.
mori:~ gen$ brew remove subversion18
Error: No such keg: /usr/local/Cellar/subversion18
mori:~ gen$ brew install subversion18 --with-unicode-path
...(snip)...
==> Summary
🍺  /usr/local/Cellar/subversion18/1.8.16: 128 files, 9.3MB, built in 2 minutes 27 seconds
mori:~ gen$ 
=====

**Comment by tholu** [comment]
It obviously was not so easy 😄 Glad I could help!
